name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-22.04
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build-debian:
    needs: create-release
    runs-on: ubuntu-22.04
    container: debian:bullseye
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            curl \
            build-essential \
            git \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libsoup2.4-dev \
            libatk1.0-dev \
            libcairo2-dev \
            libgdk-pixbuf2.0-dev \
            libglib2.0-dev \
            libpango1.0-dev \
            pkg-config \
            bash
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
      - name: Build binary
        shell: bash
        run: |
          . "$HOME/.cargo/env"
          cargo build --release
      - name: Create DEB package
        run: |
          mkdir -p debian/DEBIAN
          mkdir -p debian/usr/bin
          mkdir -p debian/usr/share/applications
          mkdir -p debian/etc/yamli-editor
          cp target/release/yamli-editor debian/usr/bin/
          cp yamli-editor.desktop debian/usr/share/applications/
          cp config.toml debian/etc/yamli-editor/
          cat > debian/DEBIAN/control << EOF
          Package: yamli-editor
          Version: ${GITHUB_REF#refs/tags/v}
          Architecture: amd64
          Maintainer: Ali <ali205412@github.com>
          Description: Native Yamli editor for Wayland
          Depends: libgtk-3-0, libwebkit2gtk-4.0-37, libsoup2.4-1
          EOF
          dpkg-deb --build debian
          mv debian.deb yamli-editor.deb
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: yamli-editor.deb
        env:
          GITHUB_TOKEN: ${{ github.token }}
